excerpt_separator: ""
highlighter: true
markdown: kramdown
url: http://mrsweaters.github.io
title: Oops I coded
tagline: My brief experiences with software engineering.
description: Emphasis on brief engineering experiences.
gems: [jekyll-paginate]
paginate: 5
